### ISSUE TITLE
🛠️ `Neighborhood`: Install `strong_migrations` to catch risky operations

### ISSUE THREAD

**Issue by KellyAH** [zinc-collective/convene#1177]
installing strong_migrations were mentioned in https://github.com/zinc-collective/convene/pull/1169#discussion_r1124954327

[strong_migrations](https://github.com/ankane/strong_migrations) will help us catch risky operations and safely ignore and drop deprecated database columns

**Comment by rosschapman** [comment]
➕ for this because I hit a bad error when setting up my environment. There are two migrations that reference a `UtilityHookup` model that no longer exists. 

`db/migrate/20210710224638_encrypt_utility_hookup_configuration.rb`
`db/migrate/20230119012952_remove_jitsi_plaid_utilities.rb`

Although, after downgrading from Postgres 14 to Postgres 12 I could _somehow_ run `db:migrate` successfully -- don't ask me why (yet! 😅).

It sounds like this gem would prevent this problem. Relatedly, what's the best way to get rid of bad/defunct migrations?

**Comment by rosschapman** [comment]
@zspencer @KellyAH perhaps this would be a good first task for me while I'm getting situated with the system, and could work on during tomorrow's huddle?

**Comment by KellyAH** [comment]
> get rid of bad/defunct migrations

Maybe https://guides.rubyonrails.org/active_record_migrations.html#schema-dumping-and-you can help.

**Comment by anaulin** [comment]
@rosschapman if you feel moved to tackle this, go for it! 💪🏼 Generally speaking, no need to ask for permission, you can just leave a note here saying that you plan to work on it, to avoid effort duplication, and take it on.

**Comment by zspencer** [comment]
Wooo !! THank you @rosschapman !!!
