### ISSUE TITLE
🐞 `Marketplace`: `Guest` `Shopper` is shown a 404 after `Checkout`

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#1657]
- https://github.com/zinc-collective/convene/issues/1326
- https://github.com/zinc-collective/convene/issues/1661

After a successful purchase from the Marketplace, a shopper got redirected to their order page (https://marketplace.piikup.com/spaces/piikup/rooms/crumbleandwhisk/marketplaces/4cad5db3-562a-4630-b31d-fc6a253ea5a9/orders/45f6c244-4e32-43c1-aa4b-8e002e278d81?stripe_session_id=cs_live_b1GZZOiJS3UGIqMKQdk5PMAPiwtdA3Me3ZXIYkePdKHoGnGYXRo4mJdtMr), but this page is only visible to logged-in users, so instead they got the standard Rails 404 page.

We should make it so that a successful order confirmation page is visible even if the user is logged-out of Convene, which is going to be the most common case. One way to do this would be to create a separate "order confirmed" page that is visible for logged out users and directs users to log into Convene to see their complete order history.

**Comment by zspencer** [comment]
I'm planning to work on this either between now and Wednesday or on Wednesday.

**Comment by zspencer** [comment]
I have been able to confirm this through the automated system test; are there any @zinc-collective/contributors interested in double-checking that the fix is "good enough?"

If so, assign this issue to yourself and run through placing an order! (Note: This is... not trivial locally due to the need to be connected to `Stripe`, so it may not be an ideal thing to tackel unless you want to work through that molasses or have already done so)

If not, I'll close this out next time I'm looking at my assigned issues.
