### ISSUE TITLE
🐞 `Marketplace`: `Buying Products`: Saving `Delivery Details` on `Checkout` when no `Cart Delivery Area` is set

### ISSUE THREAD

**Issue by anaulin** [zinc-collective/convene#1983]
- https://github.com/zinc-collective/convene/issues/1326

When a `Cart` does not have a `DeliveryArea`, you can still `Checkout`.

However, the `Checkout` screen does not have a way to set the `DeliveryArea`, and if you try to set your `DeliveryAddress` it fails to save.

**Comment by anaulin** [comment]
@zspencer now I can't get the "Checkout" button to work at all in production:

https://github.com/zinc-collective/convene/assets/6729309/da283cfd-630d-4920-9ead-8896eece9976

**Comment by zspencer** [comment]
You have no products; so you can't check out. But we should probably make that clearer...

**Comment by anaulin** [comment]
@zspencer that's not the issue, if you watch the video you'll see that i have products in my Cafe Gabriela and my Crumble carts

**Comment by anaulin** [comment]
After some more testing, I see that if I go to a vendor where I didn't already have a cart, and I select a delivery area, and also add something to my cart, then when I click the "Checkout" button it takes me to the next step.

I think there are at least two issues:
* it is not possible to visually tell the difference between an enabled and disabled "checkout" button, which makes it feel broken when you click on it and nothing happens
* there is something wonky with pre-existing carts, which might be related to the changes in https://github.com/zinc-collective/convene/pull/1992

**Comment by zspencer** [comment]
Oh dang, I saw the first one and the last one but didn't realize Cafe Gabriela had the issue too. It is odd for the Cafe Gabriela; I think it's likely that there are some `Carts` that we should delete now that we've stopped creating multiple `Carts` per `Shopper`. I'll go get rid of the carts in `pre_checkout`.

I've got a PR that removes the Checkout button completely as a kind of "stop-gap" because I didn't want to think about how to present a disabled Checkout button: https://github.com/zinc-collective/convene/pull/1999

**Comment by zspencer** [comment]
I've purged the other `Carts` that were in the `pre_checkout` state; and re-tested and it appears to work now?

**Comment by anaulin** [comment]
Does seem to work now! (There is a separate bug about the delivery area saving not updating the cart, not sure if we have a separate issue to track that.)

**Comment by zspencer** [comment]
I've created an issue https://github.com/zinc-collective/convene/issues/2002
