### ISSUE TITLE
unable to find policy `NilClassPolicy` for `nil`

### ISSUE THREAD

**Issue by codegod100** [zinc-collective/convene#755]
On new install:

![image](https://user-images.githubusercontent.com/78769380/179050588-223f9876-3dd5-467d-ac72-1c7d38b460d0.png)

**Comment by zspencer** [comment]
Hey @fuck-capitalism! This is likely because you either do not have a [`DEFAULT_SPACE` set in your `.env` file](https://github.com/zinc-collective/convene/blob/development/.env.example#L35); or the `bin/setup` script didn't successfully create a `system-test` space.

Try running the [`rake release:after_build` task, which creates the `system-test`](https://github.com/zinc-collective/convene/blob/development/lib/tasks/release.rake#L7) space; the default space for our very-early alpha build.

**Comment by zspencer** [comment]
Ahoy @codegod100 ! Just so ya know, the most recent build should resolve this! Now, folks are given a set of instructions! See https://github.com/zinc-collective/convene/pull/1141 for a brief video of the new first-run experience!
